language: node_js

git:
  # Minimize git history, but ensure to not break things:
  # - Merging multiple PR's around same time may introduce a case where it's not
  #   the last merge commit that is to be tested
  # - Aside of merge commit we need a previous commit to be able to detect a version switch
  depth: 10

cache:
  # Not relying on 'npm' shortcut, as per Travis docs it's the only 'node_modules' that it'll cache
  directories:
    - $HOME/.npm
    - node_modules

branches:
  only: # Do not build PR branches
    # Release branches
    - master
    # Release tags
    - /^v\d+\.\d+\.\d+$/ # Ensure to build release tags

stages:
  - name: Test
    if: tag IS NOT present
  - name: Tag on Release
    if: branch = master AND type = push
  - name: Deploy
    if: tag =~ ^v\d+\.\d+\.\d+$

env:
  global:
    - FORCE_COLOR=1 # Ensure colored output (color support is not detected in some cases)

# Ensure to install dependencies at their latest versions
install:
  # Note: `npm update` has issues which we need to workaround:
  # - There seems no way to update all project dependency groups in one run
  #   Hence different calls for prod and dev dependencies
  # - The bigger depth, the longer update takes (-9999 as proposed in npm docs hangs the process).
  #   Therefore we keep at 3 which should ensure most of dependencies are at latest versions
  # - Depth setting makes optional dependencies not optional (install error crashes process)
  #   Hence we skip install of optional dependencies completely, with --no-optional
  #   Note: this patch works only for npm@5+
  # - npm documents --dev option for dev dependencies update, but it's only --save-dev that works
  - npm update --depth 3 --no-optional --no-save
  - npm update --depth 3 --save-dev --no-save

before_script:
  # Fail build right after first script fails. Travis doesn't ensure that: https://github.com/travis-ci/travis-ci/issues/1066
  # More info on below line: https://www.davidpashley.com/articles/writing-robust-shell-scripts/#idm5413512
  - set -e
  - git config --global user.email "platform@serverless.com"
  - git config --global user.name "Serverless CI"

jobs:
  include:
    # In most cases it's best to configure one job per platform & Node.js version combination
    # (job boot & setup takes ca 1 minute, one task run lasts ca few seconds)

    # PR's from branches
    # Ensure commit messages follow CC, and confirm on changelog in case of release PR's
    - name: 'Prettier check updated, Lint updated, Commitlint, Changelog confirm (on release), Test - Node.js v12'
      if: type = pull_request AND fork = false
      node_js: 12
      script:
        - npm run prettier-check:updated
        - npm run lint:updated
        - npm run commitlint:pull-request
        # If release PR, confirm we have a changelog
        - |
          tagName=`git diff master package.json | grep '"version": "' | tail -n 1 | grep -oE "[0-9]+\.[0-9]+\.[0-9]+"` || :
          if [ -n "$tagName" ];
          then
            npx dump-release-notes-from-cc-changelog $tagName
          fi
        - npm test

    # PR's from forks
    # Do not validate commit messages,
    # (if user didn't ensure CC, PR should be squash merged with a valid CC commit message)
    - name: 'Prettier check updated, Lint updated, Test - Node.js v12'
      if: type = pull_request AND fork = true
      node_js: 12
      script:
        - npm run prettier-check:updated
        - npm run lint:updated
        - npm test

    # master branch
    - name: 'Test - Node.js v12'
      node_js: 12

    - name: 'Test - Node.js v13'
      node_js: 13

    - name: 'Test - Node.js v10'
      node_js: 10

    - name: 'Test - Node.js v8'
      node_js: 8

    - name: 'Test - Node.js v6'
      node_js: 6

    - stage: Tag on Release
      name: 'Tag on Release'
      node_js: 12
      env:
        # GITHUB_TOKEN
        - secure: nNfyiLgDBOD8M71EdKv4/0JK0i0VDe2cZc2AMazfTZkkp7hPDgtrVLBumGCtTpKvv5VJbOO3KAuDoB+NTAqLg87Y/K4+AigQpzHkugrj3N1XTCH+7BR/Rx0TFqcIO+YYuIp5fUAIofYg3BhY3w81P10WTuPm77C1b5bFg9UA9YLwapoZEDf0O1JBLV18Ss1/a3AlO/710CL9/ab6dQyHhM5T069nFlu7JaDdR0N6Z2VWEZMqeclI8+gB6uYLMpa4PvvqSHmyFH2lC7rf1nbBwFQ2RBhPgRvfG40Dwy968iLPmWKz9fX09N4VE2nmEtq+UVvorTcffbzml2tjUhmXFHjBGNDrtS1sBPFGMQXGE+p/oy0xIkY1McoxhnECLsLWYt57B2wuP/NM9fexFJbKAAzrri3hXyJWUWmHGJaaAfrE+OvXjAm4g7l5K/qBOmlYdDsbo4e55ISPTn8/LlpFg6JuTRiTl/eOkYDFKjJN9DpqOHGGmAxZmzXaoRux3ZxRQrBhZJrOpV8iR4bf+NNVwag35J9n42om5XLEusGHsib9hqq7wb/YAXjCRZ9/XrLwkJH9DPiOUaMk4XJS6VTH0WhZj3TBEpfk86KmiTx5EuLeRzid+QUOhgyW8HWbsVdbGBSP3NicxsjfDAU53MASmBNKluwNaLp5z+MbVv7x/rc=
      script:
        - |
          tagName=`git diff HEAD^ package.json | grep '"version": "' | tail -n 1 | grep -oE "[0-9]+\.[0-9]+\.[0-9]+"` || :
          if [ -n "$tagName" ];
          then
            git tag v$tagName
            git push -q https://$GITHUB_TOKEN@github.com/serverless/test --tags
          fi

    # version tag
    - stage: Deploy
      env:
        # GITHUB_TOKEN
        - secure: nNfyiLgDBOD8M71EdKv4/0JK0i0VDe2cZc2AMazfTZkkp7hPDgtrVLBumGCtTpKvv5VJbOO3KAuDoB+NTAqLg87Y/K4+AigQpzHkugrj3N1XTCH+7BR/Rx0TFqcIO+YYuIp5fUAIofYg3BhY3w81P10WTuPm77C1b5bFg9UA9YLwapoZEDf0O1JBLV18Ss1/a3AlO/710CL9/ab6dQyHhM5T069nFlu7JaDdR0N6Z2VWEZMqeclI8+gB6uYLMpa4PvvqSHmyFH2lC7rf1nbBwFQ2RBhPgRvfG40Dwy968iLPmWKz9fX09N4VE2nmEtq+UVvorTcffbzml2tjUhmXFHjBGNDrtS1sBPFGMQXGE+p/oy0xIkY1McoxhnECLsLWYt57B2wuP/NM9fexFJbKAAzrri3hXyJWUWmHGJaaAfrE+OvXjAm4g7l5K/qBOmlYdDsbo4e55ISPTn8/LlpFg6JuTRiTl/eOkYDFKjJN9DpqOHGGmAxZmzXaoRux3ZxRQrBhZJrOpV8iR4bf+NNVwag35J9n42om5XLEusGHsib9hqq7wb/YAXjCRZ9/XrLwkJH9DPiOUaMk4XJS6VTH0WhZj3TBEpfk86KmiTx5EuLeRzid+QUOhgyW8HWbsVdbGBSP3NicxsjfDAU53MASmBNKluwNaLp5z+MbVv7x/rc=
      node_js: 12
      script: skip
      # Ensure to fail build if deploy fails, Travis doesn't ensure that: https://github.com/travis-ci/travis-ci/issues/921
      before_deploy:
        - set -e
        # Remove eventual old npm logs
        - rm -rf ~/.npm/_logs
      after_deploy:
        - |
          # npm creates log only on failure
          if [ -d ~/.npm/_logs ]
          then
            # Undocumented way to force Travis build to fail
            travis_terminate 1
          fi
        - npx github-release-from-cc-changelog $TRAVIS_TAG
      deploy:
        provider: npm
        email: services@serverless.com
        on:
          tags: true
        api_key:
          secure: N1dW91azEh9b0RUkpcQJJ3TOiGXJ1iI1JzKLzesMZXXkvgnu6+pcDzlBy1sBaAnI3kMrVe0Q7FUah53UKEjIu/ruQ7parSjTZNr2WyRrfvWfwEpuzsNF/iUcFF/KwPbih30nPmJ4QhSQdGIi+nCQJdWcy9JXJkOG+FTqzQe08rd/pxHUsWkhVXmeuj2YtE7D02Ay7a8DySsWJ0LK3SKE/jrOE+bJm3M6Kf+LsySx/8ea4+ii24s+wWdiqx9uQex8wtXuMRL9eOIa70WrW0DTClt1c7K5pM8pUZwJR8aLNv90kH/3xju+luldLw1VE3LjG0SzEqSIHwWveTii6I82dnCTFyzK76YaAV2h+iRT2UJMBEOsI3mm44t3+XfQAQT5FMS+I+fN7TsOREPci/Z6i9/ns86I05mMo8wTDDHJvrIfAYx71MmknRnbHNPMEhvbOj9cgPYDr6vk4AKoUQxweAtcyTCy9vbScp+N39eFp27HD+6VsCZsRtwPU+G+ppP5nNR/2wBN8YxkjvKayrmG4W2S5P5SzjQJhUPeij2SqnzN5Tf3ri2LKzVe9DxIjlXD2Sztboddz8LDGJkLzt/5SGLPOi94CE1jfH8oFq2MQoFSdF95ZiWLtk6WFEDxIMWMCQ9Y/FOcjYMadsAT2buG5icYztSjFPF9VI6OavA9+mE=
